name: Generate Snake SVG

on:
  push:
    branches:
      - main

jobs:
  generate-snake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate Snake SVG
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg

      - name: Commit and push generated snake image
        run: |
          git config --global user.name "Your Name"
          git config --global user.email "youremail@example.com"
          git add dist/github-snake.svg
          git commit -m "Add generated snake image"
          git push
